project:
  type: website
  output-dir: docs

website:
  title: "S. Bassirou Diop"
  description: "This is S. Bassirou Diop's personal Blog."
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - archive.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

